apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-db-configmap
data:
  database_url: mysql-db-service
  backup-url: /backup/backup.sql
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv0001
  labels:
    app: test
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: ""
  capacity:
    storage: 5Gi
  hostPath:
    path: /home/firebelka/projects/K8s-test/pv001
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-disk
  labels:
    app: test
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: ""
  resources:
    requests:
      storage: 5Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-db
  labels:
    app: mysql-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql-db
  template:
    metadata:
      labels:
        app: mysql-db
    spec:
      containers:
      - name: mysql
        image: smth.azurecr.io/mysql-server
        ports:
        - containerPort: 3306
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: root-pwt
        - name: MYSQL_USER
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: username
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: username-pwt
        volumeMounts:
        - mountPath: "/backup/"
          name: volume
      imagePullSecrets:
      - name: docker-credentials
      volumes:
        - name: volume
          persistentVolumeClaim:
            claimName: mysql-disk
---
apiVersion: v1
kind: Service
metadata:
  name: mysql-db-service
spec:
  selector:
    app: mysql-db
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: phpmyadmin
  labels:
    app: phpmyadmin
spec:
  replicas: 1
  selector:
    matchLabels:
      app: phpmyadmin
  template:
    metadata:
      labels:
        app: phpmyadmin
    spec:
      containers:
      - name: phpmyadmin
        image: smth.azurecr.io/demo
        ports:
        - containerPort: 8081
        env:
        - name: PMA_USER
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: root
        - name: PMA_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: root-pwt
        - name: PMA_HOST
          valueFrom:
            configMapKeyRef:
              name: mysql-db-configmap
              key: database_url
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: root-pwt
      imagePullSecrets:
      - name: docker-credentials
---
apiVersion: v1
kind: Service
metadata:
  name: phpmyadmin-service
spec:
  selector:
    app: phpmyadmin
#  type: NodePort
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 80
#      nodePort: 30022
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: phpmyadmin-satging
  labels:
    app: phpmyadmin-2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: phpmyadmin-2
  template:
    metadata:
      labels:
        app: phpmyadmin-2
    spec:
      containers:
      - name: phpmyadmin-satging
        image: smth.azurecr.io/demo
        ports:
        - containerPort: 8081
        env:
        - name: PMA_USER
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: username
        - name: PMA_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: username-pwt
        - name: PMA_HOST
          valueFrom:
            configMapKeyRef:
              name: mysql-db-configmap
              key: database_url
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: root-pwt
      imagePullSecrets:
      - name: docker-credentials
---
apiVersion: v1
kind: Service
metadata:
  name: phpmyadmin-service-staging
spec:
  selector:
    app: phpmyadmin-2
  type: LoadBalancer
#  type: NodePort
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 80
#      nodePort: 30023
