apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv0001
  labels:
    app: test
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: ""
  capacity:
    storage: 5Gi
  hostPath:
    path: /home/firebelka/projects/K8s-test/mongo-dep/mongo-db-backup
