apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-disk
  labels:
    app: test
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: ""
  resources:
    requests:
      storage: 5Gi
