apiVersion: v1
kind: Secret
metadata:
    name: mysql-secret
type: Opaque
data:
    username: dXNlcm5hbWU= #echo -n 'word' | base64
    username-pwt: cGFzc3dvcmQ=
    root-pwt: QmVsa2E=
    root: cm9vdA==
    az-username: dGVzdFJlZ0s4cw==
    az-pwt: R1NtUGlWT0dVVC9EMDFPWkNHWWR5NGZuPVdPU1pzWVI=
---
apiVersion: v1
kind: Secret
metadata:
    name: docker-credentials
type: kubernetes.io/dockerconfigjson
data:
    .dockerconfigjson: eyJhdXRocyI6eyJ0ZXN0cmVnazhzLmF6dXJlY3IuaW8iOnsidXNlcm5hbWUiOiJ0ZXN0UmVnSzhzIiwicGFzc3dvcmQiOiJHU21QaVZPR1VUL0QwMU9aQ0dZZHk0Zm49V09TWnNZUiIsImVtYWlsIjoiZGFuaWxhYmVsa29AZ21haWwuY29tIiwiYXV0aCI6ImRHVnpkRkpsWjBzNGN6cEhVMjFRYVZaUFIxVlVMMFF3TVU5YVEwZFpaSGswWm00OVYwOVRXbk5aVWc9PSJ9fX0=
#kubectl create secret docker-registry regcred --docker-server=<your-registry-server> --docker-username=<your-name> --docker-password=<your-pword> --docker-email=<your-email>
#kubectl get secret regcred --output=yaml   <-------.dockerconfigjson
#https://kubernetes.io/docs/tasks/configure-pod-container/pull-image-private-registry/
