apiVersion : apps/v1
kind: Deployment
metadata:
  name: "mysql-db"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: "mysql-db"
  template:
    metadata:
      labels:
        app: "mysql-db"
    spec:
      containers:
        - name: "mysql-db"
          image: "testregk8s.azurecr.io/mysql-server"
          ports:
          - containerPort: 3306
          env:
          - name: MYSQL_ROOT_PASSWORD
            valueFrom:
              secretKeyRef:
                name: mysql-secret
                key: root-pwt
          - name: MYSQL_USER
            valueFrom:
              secretKeyRef:
                name: mysql-secret
                key: username
          - name: MYSQL_PASSWORD
            valueFrom:
              secretKeyRef:
                name: mysql-secret
                key: username-pwt
          volumeMounts:
          - mountPath: "/backup/"
            name: volume
      imagePullSecrets:
        - name: docker-credentials
      volumes:
          - name: volume
            persistentVolumeClaim:
              claimName: mysql-disk
