---
apiVersion: v1
kind: Service
metadata:
  name: phpmyadmin-service-staging
spec:
  selector:
    app: phpmyadmin-2
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 80
#      nodePort: 30023
